name: lambda-dev
channels:
  - conda-forge
  - defaults
  - flare-rpc
dependencies:
  - gcc =8.5 # [linux]
  - gxx =8.5 # [linux]
  - sysroot_linux-64=2.17 # [linux]
  - libfaiss_ex =1.7.2
  - melon
  - gtest =1.11.0
  - gmock =1.11.0